### ISSUE TITLE
Cookie not being set in Edge with fetch

### ISSUE THREAD

**Issue by colorfield** [colorfield/react_calendar#4]
When private entities are being viewed, JSON API checks the access against authentication via cookie.

For some reason Microsoft Edge does not seem to handle this well.
The [fetch documentation](https://github.com/github/fetch#sending-cookies) does not mention Edge explicitely for the 'same-origin', but it still needs to be declared in Edge 17.x, most probably because it is not the default value.

Related #1

**Comment by r-daneelolivaw** [comment]
```
fetch(endpoint, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
      // For Edge compliance.
      credentials: 'same-origin',
    })
```
should fix the issue.
